[options]
addons_path = /mnt/extra-addons, /usr/lib/python3/dist-packages/odoo/addons
http_interface = 0.0.0.0
http_port = 8069

list_db = true

db_host = dpg-d0is8oruibrs73f0tni0-a
db_port = 5432
db_user = odoo
db_password = s1v6jwLQ6npGiPJdYCsBa0JA3k1DY5v0
db_name = dbcocinadmin
db_sslmode = require

