[options]
addons_path = /mnt/extra-addons, /usr/lib/python3/dist-packages/odoo/addons
http_interface = 0.0.0.0
http_port = 8069

list_db = true

db_host = 127.0.0.200	
db_port = 5432
db_user = elcurucu_odoo-cocinadmin-user
db_password = TpNr-oD8wdlq
db_name = elcurucu_odoo-cocinadmin
db_sslmode = require

# Forzar inicialización del módulo base
--init base
