[options]
; This is the configuration file for Odoo.
; You can edit this file to change the default settings.
; For more information, see https://www.odoo.com/documentation/18.0/setup/configuration.html 

; Database
db_host = False
db_port = False
db_user = False
db_password = False

; Other options
addons_path = /mnt/extra-addons, /usr/lib/python3/dist-packages/odoo/addons
http_interface = 0.0.0.0
http_port = 8069
